global: 
  marketplace: true
  owner: quickstart-eng@amazon.com
  qsname: quickstart-datastax
  regions: 
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-west-1
    - us-west-2
  reporting: true
tests: 
  datastax: 
    parameter_input: quickstart-datastax.json
    template_file: quickstart-datastax-master.template
    regions: 
      - us-east-1
      - ap-southeast-2
      - eu-west-1
      - us-west-2
      - us-east-2
